### ISSUE TITLE
Could you explain dependencies that you are using? 

### ISSUE THREAD

**Issue by stsier** [dest4/stream-audio-fingerprint#6] opened 2018-10-08 13:39 UTC
I got the following error when i run 
**curl http://radiofg.impek.com/fg | node node_modules/stream-audio-fingerprint/codegen_demo.js**
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
100  5808    0  5808    0     0   7902      0
```

**Comment by dest4** [comment] 2018-10-08 14:32
Hi, this is a dupe of https://github.com/adblockradio/stream-audio-fingerprint/issues/2
Please install ffmpeg.
I have edited the Readme for this point to be more explicit

**Closed as completed by dest4** 2018-10-08 14:32 UTC
